### ISSUE TITLE
Forsys inputs - Create slope and road proximity rasters

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#276]
We do not have slope and road proximity (two separate layers) as the data sources are incomplete in this regard.

John Hogland provided us with the methodology and tools used for creating cost layers in ACCEL. [Tutorial](https://github.com/jshogland/SpatialModelingTutorials) and specifically [PODS example](https://github.com/jshogland/SpatialModelingTutorials/blob/main/Notebooks/PODs_Integration.ipynb).

We want to create and upload two layers:
- Slope -- [link](https://app.box.com/file/1110472009039?s=8ehz2mtmzabai5fs4cwj7ot2loz9jgot)
- Road proximity -- raster with distance to the closest road

**Comment by JanLauGe** [comment]
Hey @mskim3494 
The notebook you linked just downloads a [drive file](https://drive.google.com/file/d/1zNYZRTgNEX4mNAtU1I3-7RD8VSo8-ATH/view?usp=sharing/BMFP_Notebook_data.zip) which contains SOME Tiger road data. Are we fine to just go with that assuming it's the correct dataset? If not, how can we verify?

I'm going to get started with this since I can develop the methodology with any dummy file but we should discuss this more.

**Comment by JanLauGe** [comment]
Output is found in box.com/folder/190464876910 and will be added to the postgresDB by @elsiel23 shortly

**Comment by elsiel23** [comment]
Is this layer used for both explore and forsys?

**Comment by strangeties** [comment]
update 1:
For 300m: I found road proximity and building rasters in Box, but they needed to be masked to match the region shape.

@JanLauGe : can you please add masking logic to the raster-generation scripts (or add a comment to the script files mentioning that masking will be necessary)? I ran the following commands locally, but maybe you have better strategies:
`fire = raster('/Users/niew/cnra/Planscape/src/planscape/attributes/sierra_nevada/attributes/fire.tif')
extent(fire)
getValues(fire, 1, 1)
plot(fire)
 
m = !is.na(fire)
 
x = mask(buildings, m, "", FALSE, maskvalue=FALSE, updatevalue=NA)
 
writeRaster(x, '/Users/niew/cnra/Planscape/src/planscape/attributes/sierra_nevada/attributes/buildings.tif', overwrite=TRUE)`

update 2:
A. slope raster is not available for 300m - only for 30m. To get 300m data, we'd need to reproject to the correct CRS and adjust the scale. I tried the following commands in R, but it was taking too long to process.
`slope = raster('/Users/niew/cnra/Planscape/src/planscape/attributes/sierra_nevada/attributes/slope.tif')
 
slope_proj <- projectRaster(slope, crs=crs(m))`

@JanLauGe Since 300m is an interim solution, do you think this is still worth a shot in the short term?

**Comment by strangeties** [comment]
done for 300m data.
