### ISSUE TITLE
Change heatmap opacity

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#369]
Provide UI on left hand panel to change the opacity of ecosystem scores and slope (which are heatmaps). Location on UI for control to be provided by product.

**Comment by ayee07** [comment]
Spec: add a transparency slider below the legend
![Screenshot 2023-01-19 at 5 12 30 PM](https://user-images.githubusercontent.com/101600975/213596931-23de1975-46d8-482e-8727-628a3c9f4d8d.png)
I've also made the legend a gradient versus having 5 defined colors. I believe it feels more accurate. Could we also make the labels read left to right instead of up to down? Thanks!
