### ISSUE TITLE
Backend: Forsys: Move from constant cost to treatment-dependent costs (select cheapest available treatment for each stand) for project area ranking

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#387]
Presently, cost is a linear function of project area.

A scheme for computing costs involving selecting the cheapest treatment for each individual stand was proposed.

**Comment by strangeties** [comment]
@elsiel23 
@JanLauGe 

What's the status of treatment/cost rasters in the DB?

**Comment by JanLauGe** [comment]
It is not in the DB yet but we can add it via box.com staging if we are aligned on the logic. AFAIR, there were some discussions around the (I am going to call it) "unified cost layer". Perhaps @mskim3494 can chime in? Should I put in a merge request with R code to calculate this for the Sierra Nevada RRK area?

For reference, [here](https://github.com/OurPlanscape/Planscape/blob/main/analysis/code/forsys_tcsi_testing.Rmd#L149) is the way that I implemented the logic to derive the cost of cheapest available treatment (-> unified cost layer). The formatted Markdown output is [here](https://github.com/OurPlanscape/Planscape/blob/main/analysis/code/forsys_tcsi_testing.md) but I can't link specific lines in it.

**Comment by JanLauGe** [comment]
Capturing the state of this for posteriority and potential future work:

We explored using the cost layers provided by John Hogland. The logic we used is demonstrated in the [`forsys_tcsi_testing.md`](https://github.com/OurPlanscape/Planscape/blob/adff3a7b9b88f95e4dfa602a1da7c9ba1fae51dc/analysis/code/forsys_tcsi_testing.md) to find the cheapest available treatment in each area and wanted to assume that this would be the treatment that local land managers would be most likely to implement.

Our approach ran into two problems
1. Prescribed burn was the cheapest treatment in all locations
2. USFS scientists advised against using cost for optimisation

*Prescribed Burn*
If we were to simply choose the cheapest treatment for each stand (raster cell), then all cells would be treated with prescribed burn. In reality, this is unlikely to happen because most stands will require mechanical or hand thinning before the prescribed burn can take place. However, we did not have logic / data to understand where and when this is required, and how different types of treatment would be combined for maximum benefit. Instead, we hope that we can point end users to the right areas to focus on (where?) but leave it up to their expertise using local knowledge to decide on the right treatment (what? / how?).

*Not Optimizing for Cost*
One concern that was brought up by USFS was that optimizing for cost, i.e. preferring to treat cheap stands first, could lead to a situation where costs needed to treat the million acre target would rise every year. It would still be a good thing to include it as an optional optimization parameter available to the user, or at least to give a breakdown of projected cost for a given project area though.
