### ISSUE TITLE
Backend infrastructure for long running forsys calls

### ISSUE THREAD

**Issue by strangeties** [OurPlanscape/Planscape#390]
Ideally, project area ranking should take fewer than 5 secs.

Presently, processing time is ~2 min (30 secs for retrieving condition rasters, 1.5 min for ranking project areas).
#385 should decrease that time dramatically.

If it doesn't, we may need to look into a query queue solution. This issue is a placeholder for that effort.

**Comment by elsiel23** [comment]
We've determined that some forsys runs will take long enough that we want to call forsys asynchronously. This issue covers the work required to do that in the backend and on AWS. 

Proposed set up: https://docs.google.com/document/d/1MkrcOFayjc7g8YbX9_upN3Pmfn0555NJ3BUMT45pTqs/edit?resourcekey=0-KEVeGkF0JF2iCoIayw9m2g

**Comment by elsiel23** [comment]
We will run forsys using AWS Lambda, a serverless solution.

In order to do that, we've already completed the following milestones:
- Set up 2 queues, 2 lambdas, and associated triggers in aws to orchestrate the forsys flow
- Added a django endpoint that enqueues a message to the first SQS queue in the series.
- Successfully completed a minimal forsys run in the lambda function that uses hardcoded inputs and a small, hard-coded planning area. This run does other things like creating a scenario for testing purposes. 
- Created a directory and Dockerfile to deploy the lambda via containers

I'll close out this bug at the end of my fellowship and create smaller follow up AIs that are needed to have a fully functional e2e forsys flow

**Comment by runforyourlives** [comment]
obsolete; closing.
