### ISSUE TITLE
Zoom + panning performance is laggy with multiple maps + layers enabled

### ISSUE THREAD

**Issue by mkataria77** [OurPlanscape/Planscape#397]
Repro steps:

1. Load up planscape with 4 maps and no layers enabled
2. Try zooming in & out followed by panning on any of the 4 maps.  Performance seems pretty good and maps are all responsive on actions.
3. On Map 1, enable HUC-12 layer
4. Zoom in/out on Map 1 and the performance is noticeably slower. ~3-5s for the map to finish zooming and become responsive vs ~0-1s w/o HUC-12 layer enabled. Panning the map is also NOT possible for the ~3-5s that the map is not ready.
5. On Map 2, enable US Forests layer
6. Zoom/in out on any map and the update/readiness now seems to take ~5-7s each time.
7. On Map 3, enable one of the ecosystem score layers, e.g. Probability High Fire Severity.
8. Zoom/in out on any map. The performance is similar to the prior step of ~5-7s for the map to finish updating and be ready.
9. Repeat the process for Map 4 and the performance continues to stay at ~5-7s for the map to update & be ready.

Expected: ideally, the map refresh & readiness should remain snappy at < 1s and maintain a high rate of interactiveness.

**Comment by thequeenofspades** [comment]
Preliminary findings:
- Ecosystem score layers don't seem to noticeably affect performance
- Boundaries (e.g. HUC-12, US Forests) definitely affect performance, getting worse the more maps have a boundary layer turned on
- Zooming in/out with boundary layers enabled has worse performance than panning
- Performance with 4 maps is roughly the same as performance with 1 or 2 maps. This is expected since the hidden maps are still panning/zooming along with the visible maps, they just aren't rendered onscreen.

Possible avenues of investigation:
- Optimization techniques for Leaflet polygons
- Does enabling/disabling tooltips make a difference?
- Removing hidden maps from the DOM and not syncing pan/zoom on hidden maps

**Comment by thequeenofspades** [comment]
Closing tentatively since the smaller geojsons are in the latest alpha release. We can reopen if alpha users continue to flag performance as an issue.
