### ISSUE TITLE
Reference/target conditions

### ISSUE THREAD

**Issue by riecke** [OurPlanscape/Planscape#51]
Explain what “reference/target condition” is 
Show the reference condition for each metric 
Explain how scientists came up with it? Show the curve?

**Comment by mskim3494** [comment]
The PSW researchers have put together slides that explain the distribution of the data, what the reference condition mapped to 1 is, and the mapping (ramp function).

Either links to the slides or a saved png native to the applications should appear in the popup for normalized current conditions. If links, then the owner of the slides need to be responsible for keeping the data fresh and making sure that slide numbers that have been associated to the data (e.g., black oak stands ramp function, slide 81) do not change. Otherwise a static pdf similar to the data dictionary should be used instead.

**Comment by runforyourlives** [comment]
Closed/obsolete, though there is always a need to document where data comes from and what metrics mean.
