### ISSUE TITLE
Condition scores in plan stepper do not load

### ISSUE THREAD

**Issue by mskim3494** [OurPlanscape/Planscape#543]
`plan/scores/?id=10` fails. Attaching HAR file as well. 
[condition_score_error.har.zip](https://github.com/OurPlanscape/Planscape/files/10757953/condition_score_error.har.zip)

![image](https://user-images.githubusercontent.com/32403265/219421987-5d6f56ff-00b5-4e13-957a-5cdcb89dfd52.png)

**Comment by elsiel23** [comment]
Error due to most recent database migrations not being applied to the prod db. For some reason, django thought they were applied when they had not been. Maybe related to switching DB targets manually.

To check which migrations have been applied: python manage.py showmigrations
To revert to a previous state: python manage.py migrate plan 0009 and replace the number with the desired migration number
