### ISSUE TITLE
ForSys - Create framework for calling ForSysR from Python

### ISSUE THREAD

**Issue by JanLauGe** [OurPlanscape/Planscape#73]
Implement capability to call ForSysR from Python

**Comment by JanLauGe** [comment]
We should have a meeting to discuss #240 . 

The dummy call suggests to me that your plan is to pass on the raster data via the API call. I was operating under the assumption that the contract would be for a shape to be passed on to an R instance that would get the data for the extent of the polygon from Postgres. I think either could work, just want to make sure we're aligned :)

**Comment by strangeties** [comment]
Yes - there are a few options:
1) call R from the base Django instance
2) call R from a separate instance implemented in a) Django or b) R Shiny

My goal's implementing option 1) first so that we have a working endpoint and can understand its load limitations. Once that's done, we can decided whether to pursue 2a, 2b, or leave the endpoint as-is.

Option 2) will probably be better once we most past the alpha milestone and want to implement Patchmax runs, but it also introduces complexity that may not be worthwhile to work through for alpha. A lot of details that we work out for option 1) should be easy to port to option 2).

wdyt?

**Comment by strangeties** [comment]
I've divided this task into several smaller issues:
![image](https://user-images.githubusercontent.com/3720361/213798185-f74a5cce-0959-40ec-bd22-e1c242302d7b.png)

Would it make sense to mark this issue as obsolete and focus on the sub-issues instead?
@JanLauGe 
@riecke

**Comment by runforyourlives** [comment]
Current work to call forsys/R from python is already well underway, and obsoletes this issue.
